# Generated by Django 2.1.7 on 2019-03-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Ads',
        ),
    ]
