# Generated by Django 2.1.7 on 2019-03-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190309_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='userid',
            field=models.CharField(max_length=20),
        ),
    ]
