# Generated by Django 2.1.7 on 2019-03-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190309_0230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='userid',
            new_name='user_id',
        ),
    ]
