# Generated by Django 2.1.7 on 2019-03-09 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_loggedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userId',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='userName',
            new_name='username',
        ),
    ]
