# Generated by Django 2.1.7 on 2019-03-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190310_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='loggedIn',
            new_name='loggedin',
        ),
    ]
